apiVersion: v1
kind: Service
metadata:
  name: {{ include "sakuracloud-exporter.fullname" . }}
  labels:
    {{- include "sakuracloud-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "sakuracloud-exporter.selectorLabels" . | nindent 4 }}