# container configurations

nameOverride: ""
fullnameOverride: ""

image:
  repository: sacloud/sakuracloud_exporter
  tag: "0.11.0"
  pullPolicy: IfNotPresent

securityContext: {}
podSecurityContext: {}
resources: {}

replicaCount: 1

service:
  type: ClusterIP
  port: 9542
  # nodePort: 30000

affinity: {}

tolerations: {}

# application configurations
rateLimit: 5
debugMode: true

listenPort: 9542
metricsPath: "metrics"

token:
  token: ""
  secret: ""
  # existingTokenSecret: "sakuracloud-exporter"

noCollector:
  autoBackup: false
  coupon: false
  database: false
  internet: false
  loadBalancer: false
  localRouter: false
  mobileGateway: false
  nfs: false
  proxyLb: false
  server: false
  sim: false
  vpcRouter: false
  zone: false

fake:
  enabled: false

serviceMonitor:
  enabled: false
  labels: {}
  annotations: {}